name = "engwithme-hono-edge"
main = "src/index.ts"
compatibility_date = "2026-01-01"

[vars]
ENVIRONMENT = "production"
PHP_FALLBACK_URL = "https://engwithme-dev.tungf.io.vn/projects/EngWithMe/be/api/v1"

[[d1_databases]]
binding = "DB"
database_name = "engwithme-db"
database_id = "5b9ae72f-9e0e-4f03-9b29-4a5296e3fb79"

[ai]
binding = "AI"


